<div align="center">
  <img height="200" src="https://images8.alphacoders.com/138/1383039.png"  />
</div>

###

<h2 align="left">Hi 👋! My name is Karbyt and I'm an Engineer from Indonesia</h2>

###

<div align="left">
  <img src="https://img.shields.io/static/v1?message=Discord&logo=discord&label=&color=7289DA&logoColor=white&labelColor=&style=for-the-badge" height="35" alt="discord logo"  />
  <a href="https://facebook.com/jembyt" target="_blank">
    <img src="https://img.shields.io/static/v1?message=Facebook&logo=facebook&label=&color=1877F2&logoColor=white&labelColor=&style=for-the-badge" height="35" alt="facebook logo"  />
  </a>
  <a href="https://instagram.com/kamisatoayaka" target="_blank">
    <img src="https://img.shields.io/static/v1?message=Instagram&logo=instagram&label=&color=E4405F&logoColor=white&labelColor=&style=for-the-badge" height="35" alt="instagram logo"  />
  </a>
</div>

###

<p align="left">Then I will walk down the glory path bring asdkf by the spark. wipe out the enemies aside theres no turning back this time</p>

###

<div align="center">
  <img src="https://github-readme-stats.vercel.app/api/top-langs?username=karbyt&locale=en&hide_title=false&layout=compact&card_width=320&langs_count=5&theme=midnight-purple&hide_border=true" height="150" alt="languages graph"  />
</div>

###

<img src="https://raw.githubusercontent.com/karbyt/karbyt/output/snake.svg" alt="Snake animation" />

###
